### ISSUE TITLE
is this a bug? there are some mobs eg that are not visible in the inventory, even when spawned they are also invisible 

### ISSUE THREAD

**Issue by alfare** [ANightDazingZoroark/Borgys-Mobs#7]
![Screenshot_20210804_094602_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/128114725-99910c9d-da36-42e0-8757-1b501c420b16.jpg)

**Comment by ANightDazingZoroark** [comment]
nope, theyre a bunch of system mobs that are related to the headcrab zombies and many more. i had to make them spawnable for them to work properly but I'm still yet to figure out how to make their spawn eggs not show up in the creative inventory at the same time

**Comment by alfare** [comment]
> tidak, mereka adalah sekelompok monster sistem yang terkait dengan zombie headcrab dan banyak lagi. saya harus membuatnya dapat ditelurkan agar dapat berfungsi dengan baik, tetapi saya masih belum menemukan cara untuk membuat telur pemijahan mereka tidak muncul di inventaris kreatif pada saat yang bersamaan

oh I see, because I thought it was a bug, and it wasn't ok well then.👍

**Comment by ANightDazingZoroark** [comment]
welp alright then, time to close this

**Comment by alfare** [comment]
> baiklah kalau begitu, waktunya untuk menutup ini

Ok, alright
